import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import "simplebar-react/dist/simplebar.min.css";
import { ModeToggle } from "@/components/ToggleTheme";
import { ThemeProvider } from "@/components/themeprovider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <Providers>
        <body
          className={cn(
            "min-h-screen font-sans antialiased grainy",
            inter.className
          )}
        >
          <ThemeProvider
            attribute="data-theme"
            defaultTheme="dracula"
            enableSystem={false}
            storageKey="notes-theme2"
          >
            <ModeToggle></ModeToggle>
            <Navbar></Navbar>
            {children}
          </ThemeProvider>
        </body>
      </Providers>
    </html>
  );
}
